"""Guvenli yurutme cekirdegi.

Katmanlar policy engine, onay dogrulama, idempotency, tamper-evident audit
defteri, kalici oturum ve iki asamali tool routing'den olusur. LLM bu
modullerin hicbirini prompt ile atlatamaz; kararlar kodda uretilir.
"""

from .agents import (
    AGENT_SPECS,
    AgentSpec,
    HandoffEnvelope,
    OrchestrationPlan,
    agent_catalogue,
    handoff_from_turn,
    plan_agents,
    profiles_for_packs,
)
from .approvals import ApprovalError, ApprovalRecord, ApprovalStore, Approver, payload_hash
from .audit import (
    AuditLedger,
    CheckpointExporter,
    FileCheckpointExporter,
    NullAuditLedger,
    get_audit_ledger,
    redact,
    reset_audit_cache,
    sha256_of,
)
from .direct import (
    DIRECT_ANSWER_TOOLS,
    SHORTCUTS,
    DirectAnswer,
    DirectAnswerSpec,
    IntentShortcut,
    ShortcutMatch,
    direct_answer_for,
    match_shortcut,
    shortcut_catalogue,
)
from .execution import Verification, WriteGuard, WriteOutcome
from .idempotency import (
    ApprovalReservationConflict,
    BeginOutcome,
    BeginResult,
    IdempotencyConflict,
    IdempotencyRecord,
    IdempotencyStore,
    build_idempotency_key,
)
from .policy import (
    OBLIGATION_BLOCK_EXPORT,
    OBLIGATION_CONSUME_APPROVAL,
    OBLIGATION_DRY_RUN_FORCED,
    OBLIGATION_DUAL_CONTROL,
    OBLIGATION_EXPLAIN_ESCALATION,
    OBLIGATION_IDEMPOTENCY,
    OBLIGATION_MASK_SENSITIVE,
    OBLIGATION_READ_AFTER_WRITE,
    OBLIGATION_REASSESS_AFTER_PRICING,
    OBLIGATION_SHOW_ASSUMPTIONS,
    OBLIGATION_SHOW_DIFF,
    OBLIGATION_VERIFY_VALUE,
    OrgDefaults,
    PolicyDecision,
    PolicyDecisionPoint,
    PolicyOutcome,
    approval_payload_for,
)
from .router import (
    BOOTSTRAP_PACK,
    PACKS,
    DomainPack,
    RoutingDecision,
    domains_for_packs,
    normalize_pack_keys,
    pack_catalogue,
    route,
    schema_token_report,
    summarize_intent,
)
from .sessions import (
    SCOPE_SESSION_ADMIN,
    MemorySessionStore,
    SessionBusy,
    SessionConflict,
    SessionOwnershipError,
    SessionRecord,
    SessionStore,
    SQLiteSessionStore,
    build_session_store,
)
from .store import StateDatabase, get_state_db, reset_state_db_cache

__all__ = [
    "AGENT_SPECS",
    "DIRECT_ANSWER_TOOLS",
    "SHORTCUTS",
    "AgentSpec",
    "DirectAnswer",
    "DirectAnswerSpec",
    "IntentShortcut",
    "ShortcutMatch",
    "BOOTSTRAP_PACK",
    "HandoffEnvelope",
    "OBLIGATION_BLOCK_EXPORT",
    "OBLIGATION_CONSUME_APPROVAL",
    "OBLIGATION_DRY_RUN_FORCED",
    "OBLIGATION_DUAL_CONTROL",
    "OBLIGATION_EXPLAIN_ESCALATION",
    "OBLIGATION_IDEMPOTENCY",
    "OBLIGATION_MASK_SENSITIVE",
    "OBLIGATION_READ_AFTER_WRITE",
    "OBLIGATION_REASSESS_AFTER_PRICING",
    "OBLIGATION_SHOW_ASSUMPTIONS",
    "OBLIGATION_SHOW_DIFF",
    "OBLIGATION_VERIFY_VALUE",
    "OrgDefaults",
    "PACKS",
    "ApprovalError",
    "ApprovalRecord",
    "ApprovalReservationConflict",
    "ApprovalStore",
    "Approver",
    "AuditLedger",
    "BeginOutcome",
    "BeginResult",
    "DomainPack",
    "IdempotencyConflict",
    "IdempotencyRecord",
    "IdempotencyStore",
    "MemorySessionStore",
    "NullAuditLedger",
    "OrchestrationPlan",
    "PolicyDecision",
    "PolicyDecisionPoint",
    "PolicyOutcome",
    "RoutingDecision",
    "SCOPE_SESSION_ADMIN",
    "SQLiteSessionStore",
    "SessionBusy",
    "SessionConflict",
    "SessionOwnershipError",
    "SessionRecord",
    "SessionStore",
    "StateDatabase",
    "Verification",
    "WriteGuard",
    "WriteOutcome",
    "approval_payload_for",
    "agent_catalogue",
    "build_idempotency_key",
    "build_session_store",
    "domains_for_packs",
    "CheckpointExporter",
    "FileCheckpointExporter",
    "get_audit_ledger",
    "get_state_db",
    "handoff_from_turn",
    "normalize_pack_keys",
    "pack_catalogue",
    "payload_hash",
    "plan_agents",
    "profiles_for_packs",
    "redact",
    "reset_audit_cache",
    "reset_state_db_cache",
    "route",
    "schema_token_report",
    "sha256_of",
    "summarize_intent",
    "direct_answer_for",
    "match_shortcut",
    "shortcut_catalogue",
]
